// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8r4gyd1BK2Ao_3eFoF0yiuPOwTZU8KY',
    appId: '1:580979400430:web:895c032c3afa53cb41ddff',
    messagingSenderId: '580979400430',
    projectId: 'unisync-3b48b',
    authDomain: 'unisync-3b48b.firebaseapp.com',
    storageBucket: 'unisync-3b48b.firebasestorage.app',
    measurementId: 'G-T8QWHHQPTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK8CMxIl-WVckftUFmFZyij5fPaKNaJtg',
    appId: '1:580979400430:android:5f7ecd85854c824541ddff',
    messagingSenderId: '580979400430',
    projectId: 'unisync-3b48b',
    storageBucket: 'unisync-3b48b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl-ni_J7pdo2vmCJcNLtp007hVHif_wlI',
    appId: '1:580979400430:ios:23a2fa47583e7c4641ddff',
    messagingSenderId: '580979400430',
    projectId: 'unisync-3b48b',
    storageBucket: 'unisync-3b48b.firebasestorage.app',
    iosBundleId: 'com.unisync.app',
  );
}
